#!/usr/bin/env bash
# ============================================
# Agent ROI Demo - Setup Script
# ============================================
# Interactive setup for the Agent ROI Demo project.
# Run: ./setup.sh
#
# What it does:
#   1. Checks prerequisites (node, python, snow CLI)
#   2. Prompts for Snowflake connection details
#   3. Generates .env files from templates
#   4. Installs Node.js dependencies
#   5. Creates Python virtual environments and installs packages
#   6. Optionally runs Snowflake SQL setup scripts
#   7. Prints next steps

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_success() { echo -e "  ${GREEN}✓${NC} $1"; }
print_warning() { echo -e "  ${YELLOW}⚠${NC} $1"; }
print_error()   { echo -e "  ${RED}✗${NC} $1"; }
print_info()    { echo -e "  ${BLUE}→${NC} $1"; }

# ─── Step 1: Check Prerequisites ─────────────────────────────────────────────

print_header "Checking Prerequisites"

MISSING=0

if command -v node &>/dev/null; then
    print_success "Node.js $(node --version)"
else
    print_error "Node.js not found (required for the web app)"
    MISSING=1
fi

if command -v npm &>/dev/null; then
    print_success "npm $(npm --version)"
else
    print_error "npm not found"
    MISSING=1
fi

if command -v python3 &>/dev/null; then
    print_success "Python $(python3 --version 2>&1 | awk '{print $2}')"
else
    print_error "Python 3 not found (required for external agents)"
    MISSING=1
fi

if command -v snow &>/dev/null; then
    print_success "Snowflake CLI (snow) found"
    HAS_SNOW_CLI=1
else
    print_warning "Snowflake CLI (snow) not found - SQL setup will need to be done manually"
    HAS_SNOW_CLI=0
fi

if [ $MISSING -eq 1 ]; then
    echo ""
    print_error "Missing required tools. Please install them and re-run this script."
    exit 1
fi

# ─── Step 2: Gather Snowflake Connection Details ─────────────────────────────

print_header "Snowflake Connection Setup"

echo ""
echo "  Enter your Snowflake connection details."
echo "  Press Enter to accept defaults shown in [brackets]."
echo ""

read -p "  Snowflake Account Locator []: " SF_ACCOUNT
read -p "  Snowflake Username [admin]: " SF_USER
SF_USER=${SF_USER:-admin}
read -p "  Snowflake Role [ACCOUNTADMIN]: " SF_ROLE
SF_ROLE=${SF_ROLE:-ACCOUNTADMIN}
read -p "  Snowflake Warehouse [AGENT_ROI_WH]: " SF_WAREHOUSE
SF_WAREHOUSE=${SF_WAREHOUSE:-AGENT_ROI_WH}
read -p "  Snowflake Database [AGENT_ROI_DEMO]: " SF_DATABASE
SF_DATABASE=${SF_DATABASE:-AGENT_ROI_DEMO}
read -p "  Snowflake Schema [APP]: " SF_SCHEMA
SF_SCHEMA=${SF_SCHEMA:-APP}

echo ""
echo "  How will you authenticate?"
echo "    1) Token file (from Snowflake CLI)"
echo "    2) Programmatic Access Token (PAT) string"
read -p "  Choose [1]: " AUTH_CHOICE
AUTH_CHOICE=${AUTH_CHOICE:-1}

SF_TOKEN_FILE=""
SF_PAT=""

if [ "$AUTH_CHOICE" = "1" ]; then
    read -p "  Token file path [~/.snowflake/tokens/token]: " SF_TOKEN_FILE
    SF_TOKEN_FILE=${SF_TOKEN_FILE:-~/.snowflake/tokens/token}
else
    read -p "  PAT token: " SF_PAT
fi

if [ -z "$SF_ACCOUNT" ]; then
    print_error "Account locator is required."
    exit 1
fi

# ─── Step 3: Generate .env Files ─────────────────────────────────────────────

print_header "Generating Environment Files"

# Root .env (used by Python agents)
cat > .env << EOF
# Generated by setup.sh on $(date +%Y-%m-%d)
SNOWFLAKE_ACCOUNT=${SF_ACCOUNT}
SNOWFLAKE_USER=${SF_USER}
SNOWFLAKE_ROLE=${SF_ROLE}
SNOWFLAKE_WAREHOUSE=${SF_WAREHOUSE}
SNOWFLAKE_DATABASE=${SF_DATABASE}
SNOWFLAKE_SCHEMA=${SF_SCHEMA}
SNOWFLAKE_TOKEN_FILE=${SF_TOKEN_FILE}
SNOWFLAKE_PAT=${SF_PAT}
NEXT_PUBLIC_SNOWFLAKE_ACCOUNT=${SF_ACCOUNT}
NEXT_PUBLIC_AGENT_DATABASE=${SF_DATABASE}
NEXT_PUBLIC_AGENT_SCHEMA=${SF_SCHEMA}
NEXT_PUBLIC_AGENT_NAME=ROI_DEMO_AGENT
NEXT_PUBLIC_AGENT_WAREHOUSE=${SF_WAREHOUSE}
LLAMA_SERVER_URL=http://localhost:8080/v1
LLAMA_MODEL=qwen2.5-0.5b-instruct-q4_k_m.gguf
EOF

print_success "Created .env"

# app/.env.local (used by Next.js)
cat > app/.env.local << EOF
# Generated by setup.sh on $(date +%Y-%m-%d)
SNOWFLAKE_TOKEN_FILE=${SF_TOKEN_FILE}
SNOWFLAKE_PAT=${SF_PAT}
NEXT_PUBLIC_SNOWFLAKE_ACCOUNT=${SF_ACCOUNT}
NEXT_PUBLIC_AGENT_DATABASE=${SF_DATABASE}
NEXT_PUBLIC_AGENT_SCHEMA=${SF_SCHEMA}
NEXT_PUBLIC_AGENT_NAME=ROI_DEMO_AGENT
NEXT_PUBLIC_AGENT_WAREHOUSE=${SF_WAREHOUSE}
EOF

print_success "Created app/.env.local"

# ─── Step 4: Install Node.js Dependencies ────────────────────────────────────

print_header "Installing Node.js Dependencies"

(cd app && npm install)
print_success "Node.js packages installed"

# ─── Step 5: Create Python Virtual Environments ──────────────────────────────

print_header "Setting Up Python Environments"

# Knowledge RAG Agent (external-agent/)
print_info "Creating venv for Knowledge RAG Agent..."
python3 -m venv external-agent/.venv
source external-agent/.venv/bin/activate
pip install --quiet -r external-agent/requirements.txt
deactivate
print_success "external-agent/.venv ready"

# Local LLM Agent (external-agent/local/)
print_info "Creating venv for Local LLM Agent..."
python3 -m venv external-agent/local/.venv
source external-agent/local/.venv/bin/activate
pip install --quiet -r external-agent/local/requirements.txt
deactivate
print_success "external-agent/local/.venv ready"

# ─── Step 6: Snowflake SQL Setup (Optional) ──────────────────────────────────

print_header "Snowflake Object Setup"

echo ""
echo "  The SQL scripts in snowflake/ create databases, tables, agents,"
echo "  and other objects needed by this demo."
echo ""

if [ $HAS_SNOW_CLI -eq 1 ]; then
    read -p "  Run SQL setup scripts now? [y/N]: " RUN_SQL
    RUN_SQL=${RUN_SQL:-N}

    if [[ "$RUN_SQL" =~ ^[Yy]$ ]]; then
        print_info "Running SQL scripts..."
        for script in snowflake/[0-9]*.sql; do
            print_info "Running $(basename $script)..."
            snow sql -f "$script" --connection default 2>&1 | tail -1
        done
        print_success "All SQL scripts executed"
    else
        print_warning "Skipped. Run manually: snow sql -f snowflake/01_setup.sql"
    fi
else
    print_warning "Snowflake CLI not available. Run SQL scripts manually in Snowsight."
    print_info "Execute each file in snowflake/ in order (01 through 13)."
fi

# ─── Done! ────────────────────────────────────────────────────────────────────

print_header "Setup Complete!"

echo ""
echo "  To run the application, start these in separate terminals:"
echo ""
echo -e "  ${GREEN}Terminal 1 - Web App:${NC}"
echo "    cd app && npm run dev"
echo ""
echo -e "  ${GREEN}Terminal 2 - Knowledge RAG Agent:${NC}"
echo "    source external-agent/.venv/bin/activate"
echo "    cd external-agent && python server.py"
echo ""
echo -e "  ${GREEN}Terminal 3 - Local LLM Agent (optional):${NC}"
echo "    source external-agent/local/.venv/bin/activate"
echo "    cd external-agent/local && python server.py"
echo ""
echo -e "  ${GREEN}Terminal 4 - llama-server (optional, for Local Agent):${NC}"
echo "    llama-server -m /path/to/qwen2.5-0.5b-instruct-q4_k_m.gguf -c 2048 --port 8080"
echo ""
echo -e "  Then open ${BLUE}http://localhost:3000${NC} in your browser."
echo ""
