-- Agent ROI Demo: Infrastructure Setup
-- Run as ACCOUNTADMIN

CREATE DATABASE IF NOT EXISTS AGENT_ROI_DEMO;
CREATE SCHEMA IF NOT EXISTS AGENT_ROI_DEMO.APP;
CREATE WAREHOUSE IF NOT EXISTS AGENT_ROI_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE AGENT_ROI_DEMO;
USE SCHEMA APP;
USE WAREHOUSE AGENT_ROI_WH;
