-- Agent ROI Demo: Sample Data from TPC-H
-- Source: SFSALESSHARED_SFC_SAMPLES_PROD3_SAMPLE_DATA.TPCH_SF1

USE DATABASE AGENT_ROI_DEMO;
USE SCHEMA APP;
USE WAREHOUSE AGENT_ROI_WH;

-- Orders: 50K sample for fast demo queries
CREATE OR REPLACE TABLE AGENT_ROI_DEMO.APP.ORDERS AS
SELECT O_ORDERKEY AS order_id, O_CUSTKEY AS customer_id,
       O_TOTALPRICE AS total_price, O_ORDERDATE AS order_date,
       O_ORDERSTATUS AS status, O_ORDERPRIORITY AS priority
FROM SFSALESSHARED_SFC_SAMPLES_PROD3_SAMPLE_DATA.TPCH_SF1.ORDERS
SAMPLE (50000 ROWS);

-- All customers (150K)
CREATE OR REPLACE TABLE AGENT_ROI_DEMO.APP.CUSTOMERS AS
SELECT C_CUSTKEY AS customer_id, C_NAME AS name, C_MKTSEGMENT AS market_segment,
       C_NATIONKEY AS nation_key, C_ACCTBAL AS account_balance
FROM SFSALESSHARED_SFC_SAMPLES_PROD3_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

-- Nations (25)
CREATE OR REPLACE TABLE AGENT_ROI_DEMO.APP.NATIONS AS
SELECT N_NATIONKEY AS nation_key, N_NAME AS nation_name, N_REGIONKEY AS region_key
FROM SFSALESSHARED_SFC_SAMPLES_PROD3_SAMPLE_DATA.TPCH_SF1.NATION;

-- Regions (5)
CREATE OR REPLACE TABLE AGENT_ROI_DEMO.APP.REGIONS AS
SELECT R_REGIONKEY AS region_key, R_NAME AS region_name
FROM SFSALESSHARED_SFC_SAMPLES_PROD3_SAMPLE_DATA.TPCH_SF1.REGION;
