-- Agent ROI Demo: Knowledge Base Documents for Cortex Search
-- 20 policy/FAQ documents covering logistics, finance, operations, classification, compliance

USE DATABASE AGENT_ROI_DEMO;
USE SCHEMA APP;
USE WAREHOUSE AGENT_ROI_WH;

CREATE OR REPLACE TABLE AGENT_ROI_DEMO.APP.KNOWLEDGE_DOCS (
  doc_id      NUMBER AUTOINCREMENT,
  title       VARCHAR,
  category    VARCHAR,
  content     VARCHAR
);

INSERT INTO AGENT_ROI_DEMO.APP.KNOWLEDGE_DOCS (title, category, content) VALUES
  ('Standard Shipping Policy', 'logistics', 'Standard shipping takes 5-7 business days for domestic orders. International orders take 10-14 business days. Tracking numbers are provided within 24 hours of shipment. Free shipping is available for orders over $500 total price.'),
  ('Express Shipping Policy', 'logistics', 'Express shipping is available for orders marked with 1-URGENT or 2-HIGH priority. Express orders are processed same-day if placed before 2 PM EST. Delivery is guaranteed within 2 business days domestic, 5 days international. Additional surcharge of 15% applies.'),
  ('Refund Policy', 'finance', 'Refunds are accepted within 30 days of order delivery. Orders with status F (fulfilled) are eligible for full refund. Orders with status O (open) can be cancelled without penalty. Partial refunds available for orders with status P (partial). Account balance adjustments are processed within 48 hours.'),
  ('Account Balance Policy', 'finance', 'Customer account balances are maintained in the local currency of their nation. Negative balances below -$1000 trigger automatic account review. Balances above $10,000 qualify for preferred customer pricing tier. Balance adjustments require manager approval for amounts exceeding $5,000.'),
  ('Priority Escalation Procedures', 'operations', 'Orders marked 1-URGENT bypass the standard processing queue and receive immediate attention. 2-HIGH priority orders are processed within 4 hours. 3-MEDIUM follows standard SLA of 24 hours. 4-NOT SPECIFIED and 5-LOW are processed in batch overnight. Escalation from any priority to 1-URGENT requires operations manager approval.'),
  ('Market Segment Definitions', 'classification', 'BUILDING: Construction, infrastructure, and real estate development companies. AUTOMOBILE: Vehicle manufacturers, dealerships, and automotive parts suppliers. MACHINERY: Industrial equipment manufacturers and heavy machinery operators. HOUSEHOLD: Consumer goods companies serving residential customers. FURNITURE: Home and office furniture manufacturers and retailers.'),
  ('Regional Operations Guide - Americas', 'operations', 'The AMERICA region covers United States, Canada, Brazil, Argentina, and Peru. Regional warehouse located in Memphis, TN. Standard processing applies with no regional surcharges. Peak season runs October through December with extended processing times of 1-2 additional days.'),
  ('Regional Operations Guide - Europe', 'operations', 'The EUROPE region covers United Kingdom, France, Germany, Romania, and Russia. Regional warehouse located in Rotterdam, Netherlands. EU orders ship duty-free within the European Economic Area. Non-EU countries (Russia) subject to customs processing adding 3-5 days.'),
  ('Regional Operations Guide - Asia', 'operations', 'The ASIA region covers China, Japan, India, Indonesia, and Vietnam. Regional warehouse located in Singapore. Orders above $2000 total price qualify for air freight at no additional charge. Standard orders ship via ocean freight with 14-21 day delivery window.'),
  ('Regional Operations Guide - Middle East', 'operations', 'The MIDDLE EAST region covers Saudi Arabia, Egypt, Jordan, Iran, and Iraq. Regional warehouse located in Dubai, UAE. All orders require customs documentation. Priority orders (1-URGENT, 2-HIGH) use dedicated courier service with 3-day delivery guarantee.'),
  ('Regional Operations Guide - Africa', 'operations', 'The AFRICA region covers Ethiopia, Kenya, Algeria, Mozambique, and Morocco. Regional warehouse located in Nairobi, Kenya. Limited express options available. Standard delivery window is 14-28 days. Orders above $5000 include free insurance coverage.'),
  ('Customer Tier Classification', 'classification', 'Preferred Tier: Account balance above $10,000 - priority processing, dedicated account manager, 5% discount on all orders. Standard Tier: Account balance $1,000-$10,000 - standard processing, email support. Basic Tier: Account balance below $1,000 - standard processing, self-service support only. Negative Balance: Account under review, orders held pending balance resolution.'),
  ('Order Status Definitions', 'classification', 'Status O (Open): Order received and in processing queue. Status P (Partial): Order partially fulfilled, remaining items pending. Status F (Fulfilled): Order complete, all items shipped and delivered. Status changes are logged with timestamps for audit trail compliance.'),
  ('Data Retention Policy', 'compliance', 'Order data is retained for 7 years per financial compliance requirements. Customer account information is retained for the lifetime of the account plus 3 years after closure. Shipping and tracking data is retained for 2 years. All data subject to GDPR deletion requests for EU-region customers.'),
  ('Discount and Pricing Policy', 'finance', 'Volume discounts apply for orders exceeding $2000 total price: 5% discount for $2000-$5000, 10% for $5000-$10000, 15% for orders above $10000. Preferred tier customers receive an additional 5% on top of volume discounts. Discounts are applied at order level, not line-item level. Discounts cannot be combined with promotional offers.'),
  ('Quality Assurance Process', 'operations', 'All orders above $1000 undergo quality inspection before shipment. Inspection adds 1 business day to processing time. Orders with 1-URGENT priority skip quality inspection unless customer opts in. Defective items discovered during QA trigger automatic replacement order with 2-HIGH priority.'),
  ('Supplier Management Policy', 'operations', 'We maintain relationships with 10,000 active suppliers across all regions. Supplier performance is evaluated quarterly on delivery time, quality, and pricing. Suppliers with consistent late deliveries (>10% of orders) are placed on probation. New supplier onboarding requires 30-day evaluation period with limited order volume.'),
  ('Customer Communication Policy', 'operations', 'Order confirmation emails sent within 1 hour of order placement. Shipping notifications sent when tracking number is generated. Delivery confirmation sent upon carrier confirmation. For orders delayed beyond SLA, proactive notification is sent to customer with revised delivery estimate and 10% credit offer.'),
  ('Inventory Management', 'operations', 'Safety stock levels maintained at 15% above average monthly demand. Stockout events trigger automatic backorder with customer notification. Reorder points calculated weekly based on rolling 90-day demand. Seasonal adjustments applied for peak periods (Q4) with 25% increased safety stock.'),
  ('Compliance and Audit Requirements', 'compliance', 'All financial transactions logged with full audit trail. Monthly reconciliation of order totals against payment receipts. Quarterly internal audit of order processing times vs SLA commitments. Annual external audit of data retention and security practices. SOC 2 Type II compliance maintained for all customer data handling.');
